development:
  clients:
    default:
      database: dev_db
      hosts:
        - localhost:27017
      options:
        # Adicione opções aqui, se necessário

test:
  clients:
    default:
      database: test_db
      hosts:
        - localhost:27017