development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        ssl: true

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        ssl: true
test:
  clients:
    default:
      database: test_db
      hosts:
        - localhost:27017